# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vaja.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nvaja.proto\x12\x08vajaPack\"\x1b\n\x0bVajaRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\tVajaReply\x12\x0e\n\x06result\x18\x01 \x01(\t\")\n\nStreamData\x12\r\n\x05\x63heck\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2\xc6\x01\n\x0bVajaService\x12\x38\n\x08VajaFunc\x12\x15.vajaPack.VajaRequest\x1a\x13.vajaPack.VajaReply\"\x00\x12;\n\nVajaStream\x12\x14.vajaPack.StreamData\x1a\x13.vajaPack.VajaReply\"\x00(\x01\x12@\n\x0cVajaBiStream\x12\x14.vajaPack.StreamData\x1a\x14.vajaPack.StreamData\"\x00(\x01\x30\x01\x62\x06proto3')



_VAJAREQUEST = DESCRIPTOR.message_types_by_name['VajaRequest']
_VAJAREPLY = DESCRIPTOR.message_types_by_name['VajaReply']
_STREAMDATA = DESCRIPTOR.message_types_by_name['StreamData']
VajaRequest = _reflection.GeneratedProtocolMessageType('VajaRequest', (_message.Message,), {
  'DESCRIPTOR' : _VAJAREQUEST,
  '__module__' : 'vaja_pb2'
  # @@protoc_insertion_point(class_scope:vajaPack.VajaRequest)
  })
_sym_db.RegisterMessage(VajaRequest)

VajaReply = _reflection.GeneratedProtocolMessageType('VajaReply', (_message.Message,), {
  'DESCRIPTOR' : _VAJAREPLY,
  '__module__' : 'vaja_pb2'
  # @@protoc_insertion_point(class_scope:vajaPack.VajaReply)
  })
_sym_db.RegisterMessage(VajaReply)

StreamData = _reflection.GeneratedProtocolMessageType('StreamData', (_message.Message,), {
  'DESCRIPTOR' : _STREAMDATA,
  '__module__' : 'vaja_pb2'
  # @@protoc_insertion_point(class_scope:vajaPack.StreamData)
  })
_sym_db.RegisterMessage(StreamData)

_VAJASERVICE = DESCRIPTOR.services_by_name['VajaService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VAJAREQUEST._serialized_start=24
  _VAJAREQUEST._serialized_end=51
  _VAJAREPLY._serialized_start=53
  _VAJAREPLY._serialized_end=80
  _STREAMDATA._serialized_start=82
  _STREAMDATA._serialized_end=123
  _VAJASERVICE._serialized_start=126
  _VAJASERVICE._serialized_end=324
# @@protoc_insertion_point(module_scope)
